### ISSUE TITLE
FIx: Navbar Responsiveness

### ISSUE THREAD

**Issue by ManishBisht777** [ManishBisht777/frontend-freaks-website#11]
### Description

There are some spacing issues in navbar in mobile mode

**Comment by aishwarya-mali** [comment]
@ManishBisht777 I'd like to work on this issue.

**Comment by ManishBisht777** [comment]
> @ManishBisht777 I'd like to work on this issue.

sure @aishwarya-mali Assigned to you

**Comment by ManishBisht777** [comment]
closing this as completed
