### ISSUE TITLE
[Feat] Footer

### ISSUE THREAD

**Issue by ManishBisht777** [ManishBisht777/frontend-freaks-website#13]
### Description

Create footer for the page

**Comment by realrohitgurav** [comment]
Hi @ManishBisht777 , I've created a demo footer as shown below. Do let me know what you think of the Footer and if you'd want any additional changes. :)

![Frontend Freaks](https://github.com/ManishBisht777/frontend-freaks-website/assets/110970889/26e2d6f5-272a-4445-8f45-4b9119557e6d)

**Comment by ManishBisht777** [comment]
Look cool @realrohitgurav you can open a pr for the same :)
