### ISSUE TITLE
Bug: dark mode

### ISSUE THREAD

**Issue by ManishBisht777** [ManishBisht777/frontend-freaks-website#21]
### Description

Callouts is dark mode are looking like this

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/89926834/b198d210-31e8-45b5-82af-6347c9f7a18c)

**Comment by antonpalermo** [comment]
Hi @ManishBisht777 I'm currently working on this. Should the background be transparent when in dark mode?

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/39951999/cfc689d3-1af5-4eb4-a23c-2fa5a3addcff)

**Comment by ManishBisht777** [comment]
yeah seems good

**Comment by ManishBisht777** [comment]
assigned to you as you are working on it

but from next time please wait until you get assigned to the issue to avoid confusion b/w contributors

**Comment by antonpalermo** [comment]
I'll take a note of that one @ManishBisht777. Thank you for giving me this chance to close another issue once again.
