### ISSUE TITLE
Bug: sidebar

### ISSUE THREAD

**Issue by ManishBisht777** [ManishBisht777/frontend-freaks-website#22]
### Description

Docs sidebar in dark mode doesn't appear to be good

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/89926834/506cca82-7c37-431e-af28-95c2bb6c56e2)

**Comment by antonpalermo** [comment]
Hi @ManishBisht777 I would love to give this a shot. Would this be enough? I use the `text-foreground` on the text and `text-muted-foreground` on the header.

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/39951999/4fab70d5-7edf-471a-ae94-aace4c04b9bb)

**Comment by ManishBisht777** [comment]
Sure @antonpalermo all your 🙌

**Comment by antonpalermo** [comment]
@ManishBisht777 Sorry, I didn't notice earlier but the sidebar styles in the `/batch` is different from what I did in `/docs` page.

**Comment by ManishBisht777** [comment]
Ohh yes actually even i didn't noticed :(
