### ISSUE TITLE
[bug]: No border in newsletter form input field

### ISSUE THREAD

**Issue by mnamesujit** [ManishBisht777/frontend-freaks-website#33]
### Description

There is no border in the newsletter form input field. In small devices, the user cannot clearly see the difference between the input form and the subscribe button.

### Screenshots

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/129402570/1eef8f1b-5876-4c5d-a9c4-6144f6788f5d)

## Expected 
- there should be a light border on input form and subscribe button.

**Comment by mnamesujit** [comment]
Can you assign this issue to me?

**Comment by ManishBisht777** [comment]
Good find @mnamesujit 
It is good in light mode what you can do is make the button to not change color in dark mode just for the newsletter one

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/89926834/bbcbc34c-953a-4e13-81a0-0af0bbc88a02)

**Comment by ManishBisht777** [comment]
Assigned to you 👍

**Comment by mnamesujit** [comment]
Thankyou
