### ISSUE TITLE
[bug]: no padding around theme switcher button in mobile view

### ISSUE THREAD

**Issue by mnamesujit** [ManishBisht777/frontend-freaks-website#35]
### Description

There is no padding around theme switcher button in mobile view, in desktop view all things are working perfectly.

### Screenshots

![image](https://github.com/ManishBisht777/frontend-freaks-website/assets/129402570/dfb2901a-79d7-4a31-bcba-1549abd82bed)

**Comment by mnamesujit** [comment]
Can you assign this issue to me?

**Comment by ManishBisht777** [comment]
Cool assigned to you :)
